/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package intraloadbalancing;

import java.util.ArrayList;

/**
 * @author JGUTIERRGARC
 */
public class AllocatorAgentGUI extends javax.swing.JFrame {

    private ArrayList<HostDescription> activeHosts;

    public AllocatorAgentGUI(ArrayList<HostDescription> activeHosts) {
        this.activeHosts = activeHosts;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listHostsInformation = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        comboAllocatorLoadBalancingHeuristic = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monitoring & Allocator Agent");

        jScrollPane1.setViewportView(listHostsInformation);

        jLabel1.setText("Hosts' information");

        comboAllocatorLoadBalancingHeuristic.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Random"}));
        comboAllocatorLoadBalancingHeuristic.setName("jCBHeuristicType"); // NOI18N
        comboAllocatorLoadBalancingHeuristic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAllocatorLoadBalancingHeuristicActionPerformed(evt);
            }
        });

        jLabel2.setText("Allocator's load balancing heuristic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(comboAllocatorLoadBalancingHeuristic, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(comboAllocatorLoadBalancingHeuristic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        comboAllocatorLoadBalancingHeuristic.getAccessibleContext().setAccessibleName("jCBHeuristicType");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAllocatorLoadBalancingHeuristicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAllocatorLoadBalancingHeuristicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAllocatorLoadBalancingHeuristicActionPerformed

    protected void updateServersMonitorList() {
        listHostsInformation.setListData(activeHosts.toArray());
    }

    protected String getAllocatorLoadBalancingHeuristic() {
        return "random";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboAllocatorLoadBalancingHeuristic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listHostsInformation;
    // End of variables declaration//GEN-END:variables
}
